<?php if($page==='dashboard'): ?>
<section class="hero-grid">
    <div class="hero-copy">
        <span class="kicker"><?= e((string)$year) ?> 年度永續績效</span>
        <h2>把複雜的 ESG 數據<br>轉成清楚的決策訊號</h2>
        <p>所有數值僅統計已通過兩階段審核並鎖定的正式資料。</p>
    </div>
    <form class="year-filter" method="get"><label>檢視年度<select name="year" onchange="this.form.submit()"><?php for($y=(int)date('Y');$y>=2022;$y--): ?><option <?= $y===$year?'selected':'' ?>><?= $y ?></option><?php endfor; ?></select></label></form>
</section>
<section class="metrics-grid">
    <article class="metric featured"><span>年度總排放</span><strong><?= number_format((float)$summary['total'],2) ?></strong><small>tCO₂e</small></article>
    <article class="metric"><span>範疇一</span><strong><?= number_format((float)$summary['scope1'],2) ?></strong><small>直接排放</small></article>
    <article class="metric"><span>範疇二</span><strong><?= number_format((float)$summary['scope2'],2) ?></strong><small>能源間接</small></article>
    <article class="metric"><span>範疇三</span><strong><?= number_format((float)$summary['scope3'],2) ?></strong><small>其他間接</small></article>
</section>
<section class="dashboard-grid">
    <article class="panel chart-panel"><div class="panel-head"><div><span class="eyebrow">EMISSIONS TREND</span><h3>每月碳排趨勢</h3></div><span class="legend-dot">已核准數據</span></div><canvas id="trendChart" data-labels='<?= e(json_encode(array_column($trend,'month'))) ?>' data-values='<?= e(json_encode(array_column($trend,'value'))) ?>'></canvas></article>
    <article class="panel"><div class="panel-head"><div><span class="eyebrow">ACTION CENTER</span><h3>今日待辦</h3></div></div><div class="action-list"><a href="<?= e(url('/workflow')) ?>"><span class="action-icon amber">⌛</span><span><b><?= $pending ?> 筆</b>待審核資料<small>需要主管或委員會處理</small></span><i>→</i></a><a href="<?= e(url('/activity')) ?>"><span class="action-icon coral">!</span><span><b><?= $anomalies ?> 筆</b>異常波動<small>超過前三期平均 ±30%</small></span><i>→</i></a><a href="<?= e(url('/reports')) ?>"><span class="action-icon blue">⇩</span><span><b><?= (int)$summary['approved_count'] ?> 筆</b>正式資料<small>可匯出合規盤查清冊</small></span><i>→</i></a></div></article>
    <article class="panel"><div class="panel-head"><div><span class="eyebrow">ORGANIZATION RANKING</span><h3>各廠區排放貢獻</h3></div></div><div class="rank-list"><?php $max=max(array_map('floatval',array_column($orgRanking,'value'))?:[1]); foreach($orgRanking as $i=>$row): ?><div><span class="rank-no"><?= $i+1 ?></span><span class="rank-name"><?= e($row['org_name']) ?><i style="width:<?= $max?min(100,(float)$row['value']/$max*100):0 ?>%"></i></span><strong><?= number_format((float)$row['value'],1) ?></strong></div><?php endforeach; if(!$orgRanking): ?><p class="empty">尚無已核准資料</p><?php endif; ?></div></article>
    <article class="panel scope-card"><div><span class="eyebrow light">DISCLOSURE READINESS</span><h3>揭露準備度</h3><p>ISO 14064 清冊與 GRI 內容索引已整合至報表中心。</p></div><a class="btn light" href="<?= e(url('/reports')) ?>">前往報表中心 →</a></article>
</section>

<?php elseif($page==='organizations'): ?>
<div class="two-col"><section class="panel"><div class="panel-head"><div><span class="eyebrow">BOUNDARY MAP</span><h3>組織階層與邊界</h3></div></div><div class="org-tree"><?php foreach($organizations as $o): ?><div class="org-node <?= $o['parent_id']?'child':'' ?>"><span><?= $o['parent_id']?'↳':'◇' ?></span><div><strong><?= e($o['org_name']) ?></strong><small><?= e($o['org_code']) ?> · <?= ['operational'=>'營運控制','financial'=>'財務控制','equity'=>'股權比例'][$o['boundary_type']] ?> · 基期 <?= e((string)$o['base_year']) ?></small></div><em><?= $o['status']?'啟用':'停用' ?></em></div><?php endforeach; ?></div></section>
<?php if(has_role('ROLE_SUPER_ADMIN')): ?><section class="panel form-panel"><div class="panel-head"><div><span class="eyebrow">ADD NODE</span><h3>新增組織節點</h3></div></div><form method="post" class="form-grid"><?= csrf_field() ?><label>上層組織<select name="parent_id"><option value="">無（集團根節點）</option><?php foreach($organizations as $o): ?><option value="<?= $o['org_id'] ?>"><?= e($o['org_name']) ?></option><?php endforeach; ?></select></label><label>組織代碼<input name="org_code" required placeholder="FACTORY-TY2"></label><label class="full">組織或廠區名稱<input name="org_name" required></label><label>盤查邊界<select name="boundary_type"><option value="operational">營運控制權法</option><option value="financial">財務控制權法</option><option value="equity">股權比例法</option></select></label><label>基期年度<input name="base_year" type="number" min="2000" max="2100" value="2022" required></label><button class="btn primary full">建立節點</button></form></section><?php endif; ?></div>

<?php elseif($page==='users'): ?>
<div class="two-col"><section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">ACCESS CONTROL</span><h3>使用者與角色</h3></div><span class="count-badge"><?= count($users) ?> 人</span></div><div class="table-wrap"><table><thead><tr><th>使用者</th><th>組織</th><th>角色</th><th>最後登入</th><th>狀態</th></tr></thead><tbody><?php foreach($users as $u): ?><tr><td><strong><?= e($u['name']) ?></strong><small><?= e($u['email']) ?></small></td><td><?= e($u['org_name']??'跨組織') ?></td><td><?= e($u['role_name']) ?><small><?= e($u['role_code']) ?></small></td><td><?= e($u['last_login_at']??'尚未登入') ?></td><td><span class="status <?= $u['status']?'approved':'rejected' ?>"><?= $u['status']?'啟用':'停用' ?></span><?= $u['must_change_password']?'<small>待變更密碼</small>':'' ?></td></tr><?php endforeach; ?></tbody></table></div></section><section class="panel form-panel"><div class="panel-head"><div><span class="eyebrow">CREATE ACCOUNT</span><h3>新增使用者</h3></div></div><form method="post" class="form-grid"><?= csrf_field() ?><label class="full">姓名<input name="name" required></label><label class="full">電子郵件<input name="email" type="email" required></label><label>所屬組織<select name="org_id"><option value="">跨組織</option><?php foreach($organizations as $o): ?><option value="<?= $o['org_id'] ?>"><?= e($o['org_name']) ?></option><?php endforeach; ?></select></label><label>角色<select name="role_id"><?php foreach($roles as $r): ?><option value="<?= $r['role_id'] ?>"><?= e($r['role_name']) ?></option><?php endforeach; ?></select></label><label class="full">暫時密碼<input name="password" type="password" minlength="12" required><small>至少 12 字元；首次登入強制變更</small></label><button class="btn primary full">建立帳號</button></form></section></div>

<?php elseif($page==='password'): ?>
<section class="panel form-panel password-panel"><div class="panel-head"><div><span class="eyebrow">ACCOUNT SECURITY</span><h3>設定高強度密碼</h3></div></div><form method="post" class="form-grid"><?= csrf_field() ?><label class="full">目前密碼<input name="current_password" type="password" autocomplete="current-password" required></label><label class="full">新密碼<input name="new_password" type="password" minlength="12" autocomplete="new-password" required><small>至少 12 字元，包含英文大寫、小寫及數字</small></label><label class="full">再次輸入新密碼<input name="new_password_confirmation" type="password" minlength="12" autocomplete="new-password" required></label><button class="btn primary full">更新密碼</button></form></section>

<?php elseif($page==='sources'): ?>
<?php if(has_role('ROLE_SUPER_ADMIN','ROLE_ESG_COMMITTEE','ROLE_DEPT_REVIEWER')): ?><details class="panel form-panel" open><summary><span><span class="eyebrow">SOURCE REGISTRY</span><b>新增排放源</b></span><i>＋</i></summary><form method="post" class="form-grid six"><?= csrf_field() ?><label>所屬組織<select name="org_id" required><?php foreach($organizations as $o): ?><option value="<?= $o['org_id'] ?>"><?= e($o['org_name']) ?></option><?php endforeach; ?></select></label><label>範疇<select name="scope"><option value="scope1">Scope 1</option><option value="scope2">Scope 2</option><option value="scope3">Scope 3</option></select></label><label>ISO 類別<input type="number" name="iso_category" min="1" max="6" value="1"></label><label>排放源型態<input name="source_type" required placeholder="固定燃燒"></label><label>設備或活動名稱<input name="source_name" required placeholder="緊急柴油發電機 #1"></label><label>活動單位<input name="activity_unit" required placeholder="L / kWh / kg"></label><button class="btn primary full">新增排放源</button></form></details><?php endif; ?>
<section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">EMISSION SOURCES</span><h3>排放源主檔</h3></div><span class="count-badge"><?= count($sources) ?> 筆</span></div><div class="table-wrap"><table><thead><tr><th>組織</th><th>範疇</th><th>ISO 類別</th><th>型態</th><th>名稱</th><th>單位</th><th>狀態</th></tr></thead><tbody><?php foreach($sources as $s): ?><tr><td><?= e($s['org_name']) ?></td><td><span class="tag <?= e($s['scope']) ?>"><?= e(strtoupper($s['scope'])) ?></span></td><td>類別 <?= e((string)$s['iso_category']) ?></td><td><?= e($s['source_type']) ?></td><td><strong><?= e($s['source_name']) ?></strong></td><td><?= e($s['activity_unit']) ?></td><td><span class="status approved">啟用</span></td></tr><?php endforeach; ?></tbody></table></div></section>

<?php elseif($page==='factors'): ?>
<?php if(has_role('ROLE_SUPER_ADMIN','ROLE_ESG_COMMITTEE')): ?><details class="panel form-panel"><summary><span><span class="eyebrow">VERSION CONTROL</span><b>新增係數版本</b></span><i>＋</i></summary><form method="post" class="form-grid six"><?= csrf_field() ?><label>係數代碼<input name="factor_code" required></label><label>係數名稱<input name="factor_name" required></label><label>活動單位<input name="activity_unit" required></label><label>CO₂ 係數<input name="co2_factor" type="number" step="0.000001" value="0" required></label><label>CH₄ 係數<input name="ch4_factor" type="number" step="0.000001" value="0"></label><label>N₂O 係數<input name="n2o_factor" type="number" step="0.000001" value="0"></label><label>CH₄ GWP<input name="ch4_gwp" type="number" step="0.0001" value="28"></label><label>N₂O GWP<input name="n2o_gwp" type="number" step="0.0001" value="265"></label><label>版本<input name="version_label"></label><label class="span2">來源機構<input name="source_agency" required></label><label>生效日<input name="effective_start_date" type="date" required></label><label>截止日<input name="effective_end_date" type="date" required></label><button class="btn primary full">建立係數版本</button></form></details><?php endif; ?>
<section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">FACTOR DATABASE</span><h3>碳排係數版本庫</h3></div></div><div class="table-wrap"><table><thead><tr><th>代碼／名稱</th><th>單位</th><th>CO₂</th><th>CH₄</th><th>N₂O</th><th>有效區間</th><th>來源</th></tr></thead><tbody><?php foreach($factors as $f): ?><tr><td><strong><?= e($f['factor_name']) ?></strong><small><?= e($f['factor_code']) ?> · <?= e($f['version_label']) ?></small></td><td><?= e($f['activity_unit']) ?></td><td><?= e($f['co2_factor']) ?></td><td><?= e($f['ch4_factor']) ?></td><td><?= e($f['n2o_factor']) ?></td><td><?= e($f['effective_start_date']) ?><small>至 <?= e($f['effective_end_date']) ?></small></td><td><?= e($f['source_agency']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>

<?php elseif($page==='activity'): ?>
<?php if(!has_role('ROLE_AUDITOR')): ?><details class="panel form-panel" open><summary><span><span class="eyebrow">DATA ENTRY</span><b>新增活動數據</b></span><i>＋</i></summary><form method="post" enctype="multipart/form-data" class="form-grid six" data-activity-form><?= csrf_field() ?><label class="span2">排放源<select name="source_id" required><option value="">請選擇</option><?php foreach($sources as $s): ?><option value="<?= $s['source_id'] ?>" data-unit="<?= e($s['activity_unit']) ?>"><?= e($s['org_name'].'｜'.$s['source_name'].' ('.$s['activity_unit'].')') ?></option><?php endforeach; ?></select></label><label class="span2">係數版本<select name="factor_id" required><option value="">請選擇</option><?php foreach($factors as $f): ?><option value="<?= $f['factor_id'] ?>" data-unit="<?= e($f['activity_unit']) ?>"><?= e($f['factor_name'].'｜'.$f['effective_start_date'].'～'.$f['effective_end_date']) ?></option><?php endforeach; ?></select></label><label>年度<input type="number" name="period_year" min="2000" max="2100" value="<?= date('Y') ?>" required></label><label>月份<input type="number" name="period_month" min="1" max="12" value="<?= date('n') ?>" required></label><label>活動數據量<input type="number" name="usage_amount" min="0" step="0.0001" required></label><label class="span2">佐證附件<input type="file" name="evidence" accept=".pdf,.jpg,.jpeg,.png,.xlsx"><small>送審前至少需一份 PDF/JPG/PNG/XLSX</small></label><label class="span2">異常波動說明<textarea name="anomaly_note" placeholder="若數值波動超過前三期平均 ±30%，請說明原因"></textarea></label><button class="btn primary full">計算並儲存草稿</button></form></details><?php endif; ?>
<section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">INVENTORY DATA</span><h3><?= e((string)$year) ?> 年盤查資料</h3></div><form method="get"><select name="year" onchange="this.form.submit()"><?php for($y=(int)date('Y');$y>=2022;$y--): ?><option <?= $y===$year?'selected':'' ?>><?= $y ?></option><?php endfor; ?></select></form></div><div class="table-wrap"><table><thead><tr><th>期間／組織</th><th>排放源</th><th>活動數據</th><th>計算結果</th><th>異常</th><th>附件</th><th>狀態／操作</th></tr></thead><tbody><?php foreach($activities as $a): ?><tr><td><strong><?= e(sprintf('%04d-%02d',$a['period_year'],$a['period_month'])) ?></strong><small><?= e($a['org_name']) ?></small></td><td><span class="tag <?= e($a['scope']) ?>"><?= e(strtoupper($a['scope'])) ?></span> <?= e($a['source_name']) ?><small><?= e($a['factor_name']) ?></small></td><td><?= number_format((float)$a['usage_amount'],4) ?> <?= e($a['activity_unit']) ?></td><td><strong><?= number_format((float)$a['calculated_tco2e'],6) ?></strong><small>tCO₂e</small></td><td><?= $a['anomaly_flag']?'<span class="status rejected">'.e((string)$a['anomaly_deviation_pct']).'%</span>':'—' ?></td><td><?php foreach(parse_attachments($a['attachments']??'') as $att): ?><a class="file-link" href="<?= e(url('/attachments/'.$att['id'])) ?>">↧ <?= e($att['name']) ?></a><?php endforeach; ?></td><td><span class="status <?= e($a['status']) ?>"><?= e(['draft'=>'草稿','pending_review'=>'待初審','pending_approval'=>'待複審','approved'=>'已核准','rejected'=>'已退件'][$a['status']]) ?></span><?php if(in_array($a['status'],['draft','rejected'],true)&&!has_role('ROLE_AUDITOR')): ?><form method="post" action="<?= e(url('/activity/'.$a['data_id'].'/submit')) ?>" class="inline-form"><?= csrf_field() ?><button class="mini-button">送審</button></form><?php endif; ?></td></tr><?php endforeach; if(!$activities): ?><tr><td colspan="7" class="empty">本年度尚無活動數據</td></tr><?php endif; ?></tbody></table></div></section>

<?php elseif($page==='workflow'): ?>
<section class="workflow-board"><?php foreach($tasks as $t): ?><article class="review-card"><div class="review-top"><div><span class="tag <?= e($t['scope']) ?>"><?= e(strtoupper($t['scope'])) ?></span><strong><?= e($t['source_name']) ?></strong><small><?= e($t['org_name'].'｜'.$t['period_year'].'-'.$t['period_month']) ?></small></div><span class="status <?= e($t['status']) ?>"><?= e(['pending_review'=>'廠級初審','pending_approval'=>'委員會複審','rejected'=>'已退件'][$t['status']]) ?></span></div><div class="review-numbers"><span>活動數據<b><?= number_format((float)$t['usage_amount'],4) ?></b></span><span>計算結果<b><?= number_format((float)$t['calculated_tco2e'],6) ?> tCO₂e</b></span><span>佐證附件<b><?= (int)$t['attachment_count'] ?> 份</b></span></div><div class="attachment-list"><?php foreach(parse_attachments($t['attachments']??'') as $att): ?><a class="file-link" href="<?= e(url('/attachments/'.$att['id'])) ?>">↧ <?= e($att['name']) ?></a><?php endforeach; ?></div><?php if($t['anomaly_flag']): ?><p class="warning">異常波動 <?= e((string)$t['anomaly_deviation_pct']) ?>%：<?= e($t['anomaly_note']) ?></p><?php endif; ?><?php $canReview=($t['status']==='pending_review'&&has_role('ROLE_SUPER_ADMIN','ROLE_DEPT_REVIEWER'))||($t['status']==='pending_approval'&&has_role('ROLE_SUPER_ADMIN','ROLE_ESG_COMMITTEE')); if($canReview): ?><form method="post" action="<?= e(url('/workflow/'.$t['data_id'].'/review')) ?>" class="review-form"><?= csrf_field() ?><textarea name="comment" placeholder="審核意見（退件時必填）"></textarea><div><button name="action" value="reject" class="btn danger">退件補正</button><button name="action" value="approve" class="btn primary">審核通過</button></div></form><?php endif; ?></article><?php endforeach; if(!$tasks): ?><div class="panel empty-state"><b>目前沒有待審資料</b><p>新的填報送出後會出現在這裡。</p></div><?php endif; ?></section>

<?php elseif($page==='social'): ?>
<?php if(!has_role('ROLE_AUDITOR')): ?><details class="panel form-panel"><summary><span><span class="eyebrow">SOCIAL KPI</span><b>登錄社會責任指標</b></span><i>＋</i></summary><form method="post" class="form-grid six"><?= csrf_field() ?><label>組織<select name="org_id"><?php foreach($organizations as $o): ?><option value="<?= $o['org_id'] ?>"><?= e($o['org_name']) ?></option><?php endforeach; ?></select></label><label>年度<input name="metric_year" type="number" value="<?= date('Y') ?>"></label><label>類別<select name="category"><option value="diversity">多元平等</option><option value="safety">職業安全</option><option value="training">人才培育</option><option value="supply_chain">供應鏈</option></select></label><label>指標代碼<input name="metric_code" placeholder="GRI-403-FR" required></label><label class="span2">指標名稱<input name="metric_name" placeholder="失能傷害頻率" required></label><label>數值<input name="value" type="number" step="0.0001" required></label><label>單位<input name="unit" placeholder="% / 小時 / 人" required></label><label class="span2">備註<input name="note"></label><button class="btn primary full">儲存指標</button></form></details><?php endif; ?>
<section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">PEOPLE & SUPPLY CHAIN</span><h3>社會責任績效</h3></div></div><div class="table-wrap"><table><thead><tr><th>年度</th><th>組織</th><th>類別</th><th>指標代碼</th><th>指標</th><th>數值</th><th>備註</th></tr></thead><tbody><?php foreach($metrics as $m): ?><tr><td><?= e((string)$m['metric_year']) ?></td><td><?= e($m['org_name']) ?></td><td><?= e(['diversity'=>'多元平等','safety'=>'職業安全','training'=>'人才培育','supply_chain'=>'供應鏈'][$m['category']]) ?></td><td><span class="tag neutral"><?= e($m['metric_code']) ?></span></td><td><?= e($m['metric_name']) ?></td><td><strong><?= number_format((float)$m['value'],4) ?></strong> <?= e($m['unit']) ?></td><td><?= e($m['note']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>

<?php elseif($page==='governance'): ?>
<div class="two-col"><section class="panel"><div class="panel-head"><div><span class="eyebrow">MATERIALITY MATRIX</span><h3>重大主題優先排序</h3></div></div><div class="materiality-list"><?php foreach(array_slice($topics,0,10) as $i=>$t): ?><div><span><?= $i+1 ?></span><strong><?= e($t['topic_name']) ?></strong><small>利害關係人 <?= e($t['stakeholder_score']) ?> · 營運衝擊 <?= e($t['business_impact_score']) ?></small><b><?= e($t['priority_score']) ?></b></div><?php endforeach; if(!$topics): ?><p class="empty">尚未建立重大主題</p><?php endif; ?></div></section><?php if(!has_role('ROLE_AUDITOR')): ?><section class="panel form-panel"><div class="panel-head"><div><span class="eyebrow">TOPIC SCORING</span><h3>重大主題評分</h3></div></div><form method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="kind" value="topic"><label>年度<input name="topic_year" type="number" value="<?= date('Y') ?>"></label><label>主題名稱<input name="topic_name" required></label><label>利害關係人關注度 0–5<input name="stakeholder_score" type="number" min="0" max="5" step="0.01" required></label><label>營運衝擊度 0–5<input name="business_impact_score" type="number" min="0" max="5" step="0.01" required></label><label>權重<input name="weight" type="number" min="0.01" step="0.01" value="1"></label><button class="btn primary full">更新評分</button></form></section><?php endif; ?></div>
<?php if(!has_role('ROLE_AUDITOR')): ?><details class="panel form-panel"><summary><span><span class="eyebrow">GOVERNANCE DATA</span><b>新增治理紀錄</b></span><i>＋</i></summary><form method="post" class="form-grid six"><?= csrf_field() ?><input type="hidden" name="kind" value="record"><label>組織<select name="org_id"><?php foreach($organizations as $o): ?><option value="<?= $o['org_id'] ?>"><?= e($o['org_name']) ?></option><?php endforeach; ?></select></label><label>年度<input name="record_year" type="number" value="<?= date('Y') ?>"></label><label>類別<select name="category"><option value="board">董事會</option><option value="ethics">誠信經營</option><option value="anti_corruption">反貪腐</option><option value="training">治理訓練</option><option value="whistleblower">吹哨案件</option></select></label><label class="span2">指標名稱<input name="metric_name" required></label><label>指標值<input name="metric_value" required></label><label class="full">備註<input name="note"></label><button class="btn primary full">儲存治理紀錄</button></form></details><?php endif; ?>
<section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">GOVERNANCE RECORDS</span><h3>治理紀錄</h3></div></div><div class="table-wrap"><table><thead><tr><th>年度</th><th>組織</th><th>類別</th><th>指標</th><th>數值</th><th>備註</th></tr></thead><tbody><?php foreach($records as $r): ?><tr><td><?= e((string)$r['record_year']) ?></td><td><?= e($r['org_name']) ?></td><td><?= e($r['category']) ?></td><td><?= e($r['metric_name']) ?></td><td><strong><?= e($r['metric_value']) ?></strong></td><td><?= e($r['note']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>

<?php elseif($page==='reports'): ?>
<section class="report-grid"><article class="report-card green"><span class="report-icon">ISO</span><div><span class="eyebrow light">ISO 14064-1</span><h3>溫室氣體盤查清冊</h3><p>包含活動數據、係數版本、來源與核准後計算結果，可直接交付查證單位。</p><form method="get" action="<?= e(url('/reports/iso.csv')) ?>"><select name="year"><?php foreach($years?:[date('Y')] as $y): ?><option><?= e((string)$y) ?></option><?php endforeach; ?></select><button class="btn light">匯出 CSV</button></form></div></article><article class="report-card navy"><span class="report-icon">GRI</span><div><span class="eyebrow light">GRI CONTENT INDEX</span><h3>GRI 內容索引</h3><p>彙整社會責任指標，提供永續報告書編撰與揭露進度核對。</p><form method="get" action="<?= e(url('/reports/gri.csv')) ?>"><select name="year"><?php foreach($years?:[date('Y')] as $y): ?><option><?= e((string)$y) ?></option><?php endforeach; ?></select><button class="btn light">匯出 CSV</button></form></div></article></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">EXPORT CONTROL</span><h3>報表治理原則</h3></div></div><div class="check-list"><p><span>✓</span>僅匯出已完成兩階段審核並鎖定的盤查數據</p><p><span>✓</span>每筆數據保留係數版本、來源機構與有效期間</p><p><span>✓</span>CSV 採 UTF-8 BOM，可直接由 Microsoft Excel 2016 以上版本開啟</p></div></section>

<?php elseif($page==='audit'): ?>
<section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">IMMUTABLE AUDIT TRAIL</span><h3>最近 500 筆操作紀錄</h3></div></div><div class="table-wrap"><table><thead><tr><th>時間</th><th>使用者</th><th>動作</th><th>資料表</th><th>鍵值</th><th>IP</th><th>異動摘要</th></tr></thead><tbody><?php foreach($logs as $l): ?><tr><td><?= e($l['created_at']) ?></td><td><?= e($l['user_name']??'系統') ?></td><td><span class="tag neutral"><?= e($l['action']) ?></span></td><td><?= e($l['table_name']) ?></td><td><?= e($l['record_id']) ?></td><td><?= e($l['ip_address']) ?></td><td><details><summary>檢視 JSON</summary><pre><?= e($l['after_json']??$l['before_json']??'—') ?></pre></details></td></tr><?php endforeach; ?></tbody></table></div></section>

<?php elseif($page==='error'): ?><section class="panel empty-state"><b><?= e($errorMessage) ?></b><p>請返回上一頁檢查輸入內容；若問題持續，請聯絡系統管理員。</p><a class="btn primary" href="javascript:history.back()">返回上一頁</a></section>
<?php else: ?><section class="panel empty-state"><b>找不到這個頁面</b><a class="btn primary" href="<?= e(url('/dashboard')) ?>">回到戰情室</a></section><?php endif; ?>
